# Generated by Django 5.2 on 2025-04-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
