# Generated by Django 4.2 on 2025-04-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_description_alter_product_image_and_more'),
        ('store', '0006_alter_order_total_alter_product_image'),
    ]

    operations = [
    ]
