# Generated by Django 4.2 on 2025-05-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_user_is_verified_user_otp_code_user_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
    ]
