version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: quickuser
      POSTGRES_PASSWORD: quickpass123
      POSTGRES_DB: quickcart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # ensure this line is correctly indented
  backend:
    build: .
    volumes:
      - .:/app  # Mount your local backend code to container
    environment:
      DATABASE_URL: postgres://quickuser:quickpass123@db:5432/quickcart
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    stdin_open: true
    tty: true

volumes:
  postgres_data:
