version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: quickuser
      POSTGRES_PASSWORD: quickpass123
      POSTGRES_DB: quickcart
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432

  backend:
    build: .
    environment:
      DATABASE_URL: postgres://quickuser:quickpass123@db:5432/quickcart
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000  # Ensure Django runs on all network interfaces
    # Delay startup until db service is ready
    restart: on-failure

volumes:
  postgres_data:
